### ISSUE TITLE
Derplib not detecting if bot is mod or not

### ISSUE THREAD

**Issue by LordYusei** [MakuraYami/derplib#15]
So i'm testing Derplib out properly tonight and I try to clear the chat room. The bot is marked as a super admin but everytime I try to delete the message it says it's not a mod. I've looked through the code repeatedly and I can't figure out why it's doing this. Is it a known bug or something new? Lol.

**Comment by belldandu** [comment]
Its chatango being an ass.
Also this is slightly outdated. And has been fixed in my private version
which I can't give out. Wait till the new public version is released or fix
it yourself.

**Comment by MakuraYami** [comment]
It's a known bug. Chatango added moderation rights after I released this and how mods are parsed/stored needs to be edited to make it work again. You can debug and change this yourself quite easily. I'm not updating this version anymore due to some core flaws and am working on a rewrite which may or may not be released later.

**Comment by LordYusei** [comment]
I see. I spoke to you the other day on kik barry about the library not recognising me as admin and as soon as you got there it did. If it's a known issue i'll work on it and figure it out. Thanks for the information on it though. :)

**Comment by belldandu** [comment]
If you need assistance with this then message me on kami@im.ilp.moe
